### ISSUE TITLE
Does not compile on Heroku

### ISSUE THREAD

**Issue by FeeJai** [figo-connect/ruby-figo#17]
The installation of an app with the master branch of this gem in the Gemfile fails on heroku:

`sh: 2: Syntax error: Unterminated quoted string
sh: 2: Syntax error: Unterminated quoted string
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     Bundler::GemRequireError: There was an error while trying to load the gem 'figo'.
 !     Gem Load Error is: No such file or directory @ rb_sysopen - /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/bundler/gems/ruby-figo-257619ed8fb9/lib/../CONFIG.yml
`

It works locally though. Maybe check why your CI is failing - I assume it is the same problem

**Comment by FeeJai** [comment]
Here is a longer backtrace:

```sh: 2: Syntax error: Unterminated quoted string
sh: 2: Syntax error: Unterminated quoted string
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     Bundler::GemRequireError: There was an error while trying to load the gem 'figo'.
 !     Gem Load Error is: No such file or directory @ rb_sysopen - /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/bundler/gems/ruby-figo-257619ed8fb9/lib/../CONFIG.yml
 !     Backtrace for gem load error is:
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:471:in `initialize'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:471:in `open'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:471:in `load_file'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/bundler/gems/ruby-figo-257619ed8fb9/lib/figo.rb:33:in `<module:Figo>'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/bundler/gems/ruby-figo-257619ed8fb9/lib/figo.rb:32:in `<top (required)>'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
 !     /tmp/build_1f20d0bf6ddf341f63b62120a3db587f/decimogmbh-client-29150e6ea4c3cfae12e578fe40dc6d7754434a2a/vendor/bundle/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
```

**Comment by FeeJai** [comment]
oh, i found the reason. it does not compile due to a case sensitivity issue. Closing the ticket since there is a PR now
