### ISSUE TITLE
Figo::Error: We are very sorry, but something went wrong.

### ISSUE THREAD

**Issue by gobijan** [figo-connect/ruby-figo#26]
require 'figo'
    session = Figo::Session.new('ASHWLIkouP2O6_bgA2wWReRhletgWKHYjLqDaqb0LFfamim9RjexTo22ujRIP_cjLiRiSyQXyt2kM1eXU2XLFZQ0Hro15HikJQT_eNeT_9XQ')
    puts session.accounts.count

This unfortunately explodes with:

    Figo::Error: We are very sorry, but something went wrong.
    from /Users/bijan/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/figo-1.4.0/lib/helpers/https.rb:48:in `request'
    from /Users/bijan/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/figo-1.4.0/lib/figo.rb:157:in `query_api'
    from /Users/bijan/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/figo-1.4.0/lib/figo.rb:166:in `query_api_object'
    from /Users/bijan/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/figo-1.4.0/lib/account/api_call.rb:7:in `accounts'
    from (irb):3
    from /Users/bijan/.rbenv/versions/2.5.0-dev/bin/irb:11:in `<main>'

This error seems to come from an internal server error on the figo side.
I tried it with several ruby versions: 2.2, 2.3, 2.4 and 2.5 just to make sure that it has nothing to do with it.
Further I tried the equivalent node version using the node sdk which also gives me a 500 on the figo side.

**Comment by steinke** [comment]
Did you use the demo user?
The demo user was broken for a while, it should work now again. 
However you should just create your own user for testing since you have your own client id
Feel free to contact us via support@figo.io if you have questions.
Thx
Bianca
